/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Entertainment;

import java.sql.*;
import javax.swing.JSplitPane;

/**
 *
 * @author Ruthvik Garlapati
 */
public class EntertainmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form EntertainmentPanel
     */
    JSplitPane pane;
    Connection connection;
    String user;
    public EntertainmentPanel(JSplitPane pane, Connection connection, String user) {
        initComponents();
        this.pane = pane;
        this.connection = connection;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MoviesButton = new javax.swing.JButton();
        TourismButton = new javax.swing.JButton();

        MoviesButton.setText("Movies");
        MoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesButtonActionPerformed(evt);
            }
        });

        TourismButton.setText("Tourism");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(MoviesButton)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TourismButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(MoviesButton)
                .addGap(85, 85, 85)
                .addComponent(TourismButton)
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesButtonActionPerformed

MoviesJPanel panel = new MoviesJPanel(connection,user);
pane.setRightComponent(panel);

        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MoviesButton;
    private javax.swing.JButton TourismButton;
    // End of variables declaration//GEN-END:variables
}
