/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemAdmin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruthvik Garlapati
 */
public class CreateTheatrePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateTheatrePanel
     */
    Connection connection;
    public CreateTheatrePanel(Connection connection) {
        initComponents();
        this.connection = connection;
        populateTheatres();
    }
    private void populateTheatres(){
        try{
            PreparedStatement st = (PreparedStatement)connection.prepareStatement("select * from theatres");
            ResultSet rs = st.executeQuery();
            DefaultTableModel model = (DefaultTableModel) TheatreData.getModel();
            model.setRowCount(0);
            while(rs.next()) {
            Object row[] = new Object[5];
            row[0] = rs.getString(1);
            row[1] =  rs.getString(2);
            row[2] = rs.getString(3);
            row[3] = rs.getString(4);
             row[4] = rs.getString(5);
            model.addRow(row);
        }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TheatreData = new javax.swing.JTable();
        NameFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameFld1 = new javax.swing.JTextField();
        LocationLabel = new javax.swing.JLabel();
        NameFld2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SetLocationLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TheatreData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Location", "Latitude ", "Longitude"
            }
        ));
        jScrollPane1.setViewportView(TheatreData);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 93, 676, 197));
        add(NameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 327, 238, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Theatres");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 145, 47));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 343, -1, -1));
        add(NameFld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 485, 238, 50));

        LocationLabel.setForeground(new java.awt.Color(255, 255, 255));
        LocationLabel.setText("Location :");
        add(LocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 420, -1, -1));
        add(NameFld2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 404, 238, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Co-Ordinates :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 501, -1, -1));

        SetLocationLabel.setForeground(new java.awt.Color(255, 255, 255));
        SetLocationLabel.setText("Set Location");
        SetLocationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SetLocationLabelMouseReleased(evt);
            }
        });
        add(SetLocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 501, -1, -1));

        SubmitButton.setText("Submit");
        add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 563, 140, 41));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Libraries/Salle Dolby du Pathé Beaugrenelle - Frédéric Berthet.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -2, 780, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void SetLocationLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetLocationLabelMouseReleased
//MapsFrame frame  = new MapsFrame();
// frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SetLocationLabelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JTextField NameFld;
    private javax.swing.JTextField NameFld1;
    private javax.swing.JTextField NameFld2;
    private javax.swing.JLabel SetLocationLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTable TheatreData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
