/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Education.EducationPanel;
import Employment.EmployementPanel;
import Healtcare.HealthcarePanel;
import Entertainment.EntertainmentPanel;
import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.SwingUtilities;
import smartcityproject.MainJFrame;
/**
 *
 * @author Ruthvik Garlapati
 */
public class UserLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserLandingJPanel
     */
    Connection connection;
    String user;
 private static final int MIN_ZOOM = 0;
 private static final int MAX_ZOOM = 21;
 private static int zoomValue = 5;
    public UserLandingJPanel(Connection connection) {
        initComponents();
        this.connection = connection;
          UsernameLabel.setText(user + "!!");
   getMarkers();
   open_site();
    }

     String str = "";
    private void getMarkers(){
        
        try {
                    PreparedStatement st = (PreparedStatement)connection.prepareStatement("select lat,lon from bookings where user_id = 1");
                    ResultSet rs2 = st.executeQuery();
                    while(rs2.next()){
                    str += "['Message 1',"+rs2.getString(1)+","+rs2.getString(2)+",4],\n";
                    }
                    System.out.println(str);
             
                } catch (HeadlessException | SQLException sqlException) {
                    sqlException.printStackTrace();
                } 
    }
 private void open_site() {
   String fourth = "var marker, i;\n\nfor (i = 0; i < locations.length; i++) {  \n  marker = new google.maps.Marker({\n\tposition: new google.maps.LatLng(locations[i][1], locations[i][2]),\n\tmap: map,\n\tlabel: locations[i][0], \n\toptimized: true\n });\n}";
   String first = "var locations = [\n";
   String third = "];\n";
   //String second = "['Booking 1', -33.890542, 151.274856, 4],\n['Booking 2', -33.923036, 151.259052, 5]\n";
   String setMarkerScript = first + str + third + fourth;
   EngineOptions options =
     EngineOptions.newBuilder(HARDWARE_ACCELERATED).licenseKey("1BNDHFSC1G4NNJSWIB7FX6CBOWWCX8MKR14WNT2DH9XV6YW9EOWTXHCOQSIKV88D6J65JS").build();
   Engine engine = Engine.newInstance(options);
   Browser browser = engine.newBrowser();
   SwingUtilities.invokeLater(() -> {
     BrowserView view = BrowserView.newInstance(browser);
     browser.mainFrame().ifPresent(frame ->
       frame.executeJavaScript(setMarkerScript));
     ZoomIN.addActionListener(e -> {
       if (zoomValue < MAX_ZOOM) {
         browser.mainFrame().ifPresent(frame ->
           frame.executeJavaScript("map.setZoom(" +
             ++zoomValue + ")"));
       }
     });
     ZoomOut.addActionListener(e -> {
       if (zoomValue > MIN_ZOOM) {
         browser.mainFrame().ifPresent(frame ->
           frame.executeJavaScript("map.setZoom(" +
             --zoomValue + ")"));
       }
     });
     setMarkerButton.addActionListener(e ->
       browser.mainFrame().ifPresent(frame ->
         frame.executeJavaScript(setMarkerScript)));
     MapsPanel.add(view, BorderLayout.CENTER);
     String rootPath = System.getProperty("user.dir");
     browser.navigation().loadUrl("D:/NEU_JAVA_WORKSPACE/JavaSwingHospitalApplication/TestingProject/build/classes/Libraries/simple_map.html");
   });
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserLandingJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EduButton = new javax.swing.JButton();
        HealthButton = new javax.swing.JButton();
        EmployementButton = new javax.swing.JButton();
        EntertainmentButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UserSplitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MapsPanel = new javax.swing.JPanel();
        ZoomIN = new javax.swing.JButton();
        ZoomOut = new javax.swing.JButton();
        setMarkerButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 650));

        UserLandingJPanel.setBackground(new java.awt.Color(0, 153, 153));
        UserLandingJPanel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        UserLandingJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Hi..");
        UserLandingJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 26, 54, -1));

        EduButton.setBackground(new java.awt.Color(0, 204, 204));
        EduButton.setText("Education");
        EduButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EduButtonActionPerformed(evt);
            }
        });
        UserLandingJPanel.add(EduButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 96, 33));

        HealthButton.setBackground(new java.awt.Color(255, 102, 102));
        HealthButton.setText("Healthcare");
        HealthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthButtonActionPerformed(evt);
            }
        });
        UserLandingJPanel.add(HealthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, 33));

        EmployementButton.setBackground(new java.awt.Color(255, 255, 102));
        EmployementButton.setText("Employment");
        EmployementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployementButtonActionPerformed(evt);
            }
        });
        UserLandingJPanel.add(EmployementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 33));

        EntertainmentButton.setBackground(new java.awt.Color(255, 153, 255));
        EntertainmentButton.setText("Entertainment");
        EntertainmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertainmentButtonActionPerformed(evt);
            }
        });
        UserLandingJPanel.add(EntertainmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 123, 33));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-page-48.png"))); // NOI18N
        UserLandingJPanel.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 81, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-logout-rounded-50.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        UserLandingJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(242, 242, 242));

        UserSplitPane.setDividerLocation(150);
        UserSplitPane.setMinimumSize(new java.awt.Dimension(150, 1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        UserSplitPane.setLeftComponent(jPanel2);

        MapsPanel.setLayout(new javax.swing.BoxLayout(MapsPanel, javax.swing.BoxLayout.LINE_AXIS));

        ZoomIN.setText("Zoom In");

        ZoomOut.setText("Zoom Out");

        setMarkerButton.setText("Show Markers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(ZoomIN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ZoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(setMarkerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(MapsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZoomIN)
                    .addComponent(ZoomOut)
                    .addComponent(setMarkerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(MapsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        UserSplitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(UserSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UserLandingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UserLandingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(UserSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EduButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EduButtonActionPerformed

        EducationPanel panel = new EducationPanel(UserSplitPane);
        UserSplitPane.setLeftComponent(panel);
        UserSplitPane.setDividerLocation(150);
    }//GEN-LAST:event_EduButtonActionPerformed

    private void HealthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthButtonActionPerformed
        HealthcarePanel panel = new HealthcarePanel();
        UserSplitPane.setLeftComponent(panel);
        UserSplitPane.setDividerLocation(150);
    }//GEN-LAST:event_HealthButtonActionPerformed

    private void EmployementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployementButtonActionPerformed
        EmployementPanel panel = new  EmployementPanel();
        UserSplitPane.setLeftComponent(panel);
        UserSplitPane.setDividerLocation(150);
    }//GEN-LAST:event_EmployementButtonActionPerformed

    private void EntertainmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntertainmentButtonActionPerformed
        EntertainmentPanel panel = new EntertainmentPanel(UserSplitPane,connection,user);
        UserSplitPane.setLeftComponent(panel);
        UserSplitPane.setDividerLocation(150);
    }//GEN-LAST:event_EntertainmentButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        MainJFrame  frame = new MainJFrame();
        frame.show();
//        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EduButton;
    private javax.swing.JButton EmployementButton;
    private javax.swing.JButton EntertainmentButton;
    private javax.swing.JButton HealthButton;
    private javax.swing.JLabel HomeButton;
    private javax.swing.JPanel MapsPanel;
    private javax.swing.JPanel UserLandingJPanel;
    private javax.swing.JSplitPane UserSplitPane;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton ZoomIN;
    private javax.swing.JButton ZoomOut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton setMarkerButton;
    // End of variables declaration//GEN-END:variables
}
