/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.sql.Connection;

import com.teamdev.jxbrowser.browser.Browser;
import com.teamdev.jxbrowser.engine.Engine;
import com.teamdev.jxbrowser.engine.EngineOptions;
import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ruthvik Garlapati
 */
public class UserDashBoardMapsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDashBoardMapsPanel
     */
     Connection connection;
    String user;
 private static final int MIN_ZOOM = 0;
 private static final int MAX_ZOOM = 21;
 private static int zoomValue = 5;
    public UserDashBoardMapsPanel(Connection connection) {
        initComponents();
         this.connection = connection;
          //UsernameLabel.setText(user + "!!");
   getMarkers();
   open_site();
    }
 String str = "";
    private void getMarkers(){
        
        try {
                    PreparedStatement st = (PreparedStatement)connection.prepareStatement("select lat,lon from bookings where user_id = 1");
                    ResultSet rs2 = st.executeQuery();
                    while(rs2.next()){
                    str += "['Message 1',"+rs2.getString(1)+","+rs2.getString(2)+",4],\n";
                    }
                    System.out.println(str);
             
                } catch (HeadlessException | SQLException sqlException) {
                    sqlException.printStackTrace();
                } 
    }
 private void open_site() {
   String fourth = "var marker, i;\n\nfor (i = 0; i < locations.length; i++) {  \n  marker = new google.maps.Marker({\n\tposition: new google.maps.LatLng(locations[i][1], locations[i][2]),\n\tmap: map,\n\tlabel: locations[i][0], \n\toptimized: true\n });\n}";
   String first = "var locations = [\n";
   String third = "];\n";
   //String second = "['Booking 1', -33.890542, 151.274856, 4],\n['Booking 2', -33.923036, 151.259052, 5]\n";
   String setMarkerScript = first + str + third + fourth;
   EngineOptions options =
     EngineOptions.newBuilder(HARDWARE_ACCELERATED).licenseKey("1BNDHFSC1G4NNJSWIB7FX6CBOWWCX8MKR14WNT2DH9XV6YW9EOWTXHCOQSIKV88D6J65JS").build();
   Engine engine = Engine.newInstance(options);
   Browser browser = engine.newBrowser();
   SwingUtilities.invokeLater(() -> {
     BrowserView view = BrowserView.newInstance(browser);
     browser.mainFrame().ifPresent(frame ->
       frame.executeJavaScript(setMarkerScript));
     ZoomIN.addActionListener(e -> {
       if (zoomValue < MAX_ZOOM) {
         browser.mainFrame().ifPresent(frame ->
           frame.executeJavaScript("map.setZoom(" +
             ++zoomValue + ")"));
       }
     });
     ZoomOut.addActionListener(e -> {
       if (zoomValue > MIN_ZOOM) {
         browser.mainFrame().ifPresent(frame ->
           frame.executeJavaScript("map.setZoom(" +
             --zoomValue + ")"));
       }
     });
     setMarkers.addActionListener(e ->
       browser.mainFrame().ifPresent(frame ->
         frame.executeJavaScript(setMarkerScript)));
     MapsPanel.add(view, BorderLayout.CENTER);
     String rootPath = System.getProperty("user.dir");
     browser.navigation().loadUrl("D:/NEU_JAVA_WORKSPACE/JavaSwingHospitalApplication/TestingProject/build/classes/Libraries/simple_map.html");
   });
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZoomIN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ZoomOut = new javax.swing.JButton();
        setMarkers = new javax.swing.JButton();
        MapsPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ZoomIN.setText("Zoom In");
        ZoomIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomINActionPerformed(evt);
            }
        });
        add(ZoomIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 63, 145, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("Your Purchases on Map");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 17, 270, -1));

        ZoomOut.setText("Zoom Out");
        add(ZoomOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 63, 145, -1));

        setMarkers.setText("Show Markers");
        add(setMarkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 63, 122, -1));

        MapsPanel.setLayout(new javax.swing.BoxLayout(MapsPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(MapsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 880, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void ZoomINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZoomINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MapsPanel;
    private javax.swing.JButton ZoomIN;
    private javax.swing.JButton ZoomOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton setMarkers;
    // End of variables declaration//GEN-END:variables
}
