/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Education.EducationPanel;
import Employment.EmployementPanel;
import Entertainment.EntertainmentPanel;
import Entertainment.MoviesJFrame;
import Healtcare.HealthcarePanel;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JFrame;
import smartcityproject.MainJFrame;
/**
 *
 * @author Ruthvik Garlapati
 */
public class UserLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserLandingJPanel
     */
    Connection connection;
    String user;
 private static final int MIN_ZOOM = 0;
 private static final int MAX_ZOOM = 21;
 private static int zoomValue = 5;
    public UserLandingJPanel(Connection connection,String user) {
        initComponents();
        this.connection = connection;
        this.user = user;
//          UsernameLabel.setText(user + "!!");
          //UserAnalyticsDashboard board1 = new UserAnalyticsDashboard();
         // BarChartPanel.add("UserAnalyticsDashboard",board1);
                            //CardLayout layout = (CardLayout) BarChartPanel.getLayout();
                            //layout.next(BarChartPanel);
          //UserDashBoardMapsPanel panel = new UserDashBoardMapsPanel(connection);
  //UserSplitPane.setRightComponent(panel);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserTabbedPane = new javax.swing.JTabbedPane();
        educationMainJPanel1 = new Education.EducationMainJPanel();
        employementMainJPanel1 = new Employment.EmployementMainJPanel();
        healthcareMainJPanel1 = new Healtcare.HealthcareMainJPanel();
        entertainmentMainJPanel1 = new Entertainment.EntertainmentMainJPanel();
        MoviesButton = new javax.swing.JLabel();
        BookATicketLabal = new javax.swing.JLabel();
        userProfileJPanel1 = new UI.UserProfileJPanel();

        setPreferredSize(new java.awt.Dimension(1080, 650));

        UserTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout educationMainJPanel1Layout = new javax.swing.GroupLayout(educationMainJPanel1);
        educationMainJPanel1.setLayout(educationMainJPanel1Layout);
        educationMainJPanel1Layout.setHorizontalGroup(
            educationMainJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        educationMainJPanel1Layout.setVerticalGroup(
            educationMainJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        UserTabbedPane.addTab("Education", educationMainJPanel1);
        UserTabbedPane.addTab("Employment", employementMainJPanel1);
        UserTabbedPane.addTab("HealthCare", healthcareMainJPanel1);

        MoviesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-movies-tv-96.png"))); // NOI18N
        MoviesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoviesButtonMouseClicked(evt);
            }
        });

        BookATicketLabal.setText("Book a Ticket");

        javax.swing.GroupLayout entertainmentMainJPanel1Layout = new javax.swing.GroupLayout(entertainmentMainJPanel1);
        entertainmentMainJPanel1.setLayout(entertainmentMainJPanel1Layout);
        entertainmentMainJPanel1Layout.setHorizontalGroup(
            entertainmentMainJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entertainmentMainJPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(entertainmentMainJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(entertainmentMainJPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BookATicketLabal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MoviesButton))
                .addContainerGap(714, Short.MAX_VALUE))
        );
        entertainmentMainJPanel1Layout.setVerticalGroup(
            entertainmentMainJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entertainmentMainJPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(MoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookATicketLabal)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        UserTabbedPane.addTab("Entertainment", entertainmentMainJPanel1);
        UserTabbedPane.addTab("Profile", userProfileJPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MoviesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesButtonMouseClicked

MoviesJFrame frame = new MoviesJFrame();
frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookATicketLabal;
    private javax.swing.JLabel MoviesButton;
    private javax.swing.JTabbedPane UserTabbedPane;
    private Education.EducationMainJPanel educationMainJPanel1;
    private Employment.EmployementMainJPanel employementMainJPanel1;
    private Entertainment.EntertainmentMainJPanel entertainmentMainJPanel1;
    private Healtcare.HealthcareMainJPanel healthcareMainJPanel1;
    private UI.UserProfileJPanel userProfileJPanel1;
    // End of variables declaration//GEN-END:variables
}
