/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package smartcityproject;

import javax.swing.JSplitPane;

/**
 *
 * @author Ruthvik Garlapati
 */
public class EducationPanel extends javax.swing.JPanel {

    /**
     * Creates new form EducationPanel
     */
    JSplitPane pane;
    public EducationPanel(JSplitPane pane) {
        initComponents();
        this.pane = pane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniversityButton = new javax.swing.JButton();
        CollegeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        UniversityButton.setBackground(new java.awt.Color(0, 204, 204));
        UniversityButton.setText("University");
        UniversityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniversityButtonActionPerformed(evt);
            }
        });

        CollegeButton.setBackground(new java.awt.Color(0, 204, 204));
        CollegeButton.setText("College");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CollegeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UniversityButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(UniversityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(CollegeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UniversityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniversityButtonActionPerformed
EducationMainJPanel panel = new EducationMainJPanel();
pane.setRightComponent(panel);
        // TODO add your handling code here:
    }//GEN-LAST:event_UniversityButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CollegeButton;
    private javax.swing.JButton UniversityButton;
    // End of variables declaration//GEN-END:variables
}
